/* ============================================================
   DASHBOARD PAGE — Main overview / homepage
   
   Displays:
   - Key portfolio metrics (stat cards)
   - Portfolio value chart (mini)
   - Recent trades (last 5)
   - Active positions snapshot
   - Recent activity feed
   
   All data is generated by the simulator.
   In production, replace simulator calls with tunnel data.
   ============================================================ */

'use client';

import { useState, useEffect } from 'react';
import {
  DollarSign,
  TrendingUp,
  BarChart3,
  Target,
  Zap,
  Award,
  Shield,
  Activity,
} from 'lucide-react';
import ClientLayout from '@/components/ClientLayout';
import StatCard from '@/components/StatCard';
import PortfolioChart from '@/components/PortfolioChart';
import TradeTable from '@/components/TradeTable';
import PositionsList from '@/components/PositionsList';
import ActivityFeed from '@/components/ActivityFeed';
import {
  generateDashboardStats,
  generatePortfolioHistory,
  generateTradeHistory,
  generatePositions,
  generateActivityLogs,
  generateTrade,
  SIMULATED_MARKETS,
} from '@/lib/simulator';
import { DashboardStats, PortfolioSnapshot, Trade, Position, ActivityLog } from '@/lib/types';
import { formatCurrency, formatPercent } from '@/lib/utils';

export default function DashboardPage() {
  /* ---- State for all dashboard data ---- */
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [portfolio, setPortfolio] = useState<PortfolioSnapshot[]>([]);
  const [trades, setTrades] = useState<Trade[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [logs, setLogs] = useState<ActivityLog[]>([]);

  /* ---- Initialize data on mount ---- */
  useEffect(() => {
    setStats(generateDashboardStats());
    setPortfolio(generatePortfolioHistory(30));
    setTrades(generateTradeHistory(10));
    setPositions(generatePositions());
    setLogs(generateActivityLogs(15));
  }, []);

  /* ---- Simulate live updates ---- */
  useEffect(() => {
    /* Add a new trade every 20 seconds */
    const tradeInterval = setInterval(() => {
      const newTrade = generateTrade(SIMULATED_MARKETS);
      setTrades((prev) => [newTrade, ...prev].slice(0, 10));
    }, 20000);

    /* Update stats every 10 seconds */
    const statsInterval = setInterval(() => {
      setStats(generateDashboardStats());
    }, 10000);

    return () => {
      clearInterval(tradeInterval);
      clearInterval(statsInterval);
    };
  }, []);

  /* Loading state */
  if (!stats) {
    return (
      <ClientLayout>
        <div className="flex items-center justify-center h-96">
          <div className="text-accent-green font-mono text-glow-green">
            <pre className="text-xs">{`
> INITIALIZING POLYBOT TERMINAL...
> LOADING KERNEL MODULES......... [OK]
> CONNECTING TO MARKET FEED...... [OK]
> LOADING PORTFOLIO DATA.........
            `}</pre>
            <span className="cursor-blink text-accent-green"> </span>
          </div>
        </div>
      </ClientLayout>
    );
  }

  return (
    <ClientLayout>
      {/* ---- Page header — Retro ASCII ---- */}
      <div className="mb-6">
        <pre className="text-xs text-text-muted font-mono select-none">────────────────────────────────────────</pre>
        <h1 className="text-xl font-bold tracking-widest text-glow-green font-mono">
          {'>'} DASHBOARD_
        </h1>
        <p className="text-xs text-text-secondary mt-1 font-mono">
          // Real-time overview of AI trading operations
        </p>
        <pre className="text-xs text-text-muted font-mono select-none">────────────────────────────────────────</pre>
      </div>

      {/* ---- Stat cards grid ---- */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard
          label="Portfolio Value"
          value={formatCurrency(stats.portfolioValue)}
          change={formatPercent(stats.dailyChangePercent)}
          icon={DollarSign}
          variant="green"
        />
        <StatCard
          label="Total P&L"
          value={formatCurrency(stats.totalPnL)}
          change={formatPercent(stats.totalPnLPercent)}
          icon={TrendingUp}
          variant={stats.totalPnL >= 0 ? 'green' : 'red'}
        />
        <StatCard
          label="Win Rate"
          value={`${stats.winRate}%`}
          icon={Target}
          variant="cyan"
        />
        <StatCard
          label="Total Trades"
          value={stats.totalTrades.toString()}
          icon={Zap}
          variant="amber"
        />
      </div>

      {/* ---- Second row: more stats ---- */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard
          label="Sharpe Ratio"
          value={stats.sharpeRatio.toFixed(2)}
          icon={Award}
          variant="cyan"
        />
        <StatCard
          label="Max Drawdown"
          value={`-${stats.maxDrawdown}%`}
          icon={Shield}
          variant="red"
        />
        <StatCard
          label="Active Positions"
          value={stats.activePositions.toString()}
          icon={BarChart3}
          variant="green"
        />
        <StatCard
          label="Daily Change"
          value={formatCurrency(stats.dailyChange)}
          change={formatPercent(stats.dailyChangePercent)}
          icon={Activity}
          variant={stats.dailyChange >= 0 ? 'green' : 'red'}
        />
      </div>

      {/* ---- Main content: Chart + Activity ---- */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        {/* Portfolio chart — takes 2/3 of the width */}
        <div className="lg:col-span-2 card p-4">
          <h2 className="text-xs font-bold text-foreground mb-4 flex items-center gap-2 font-mono">
            <span className="text-text-muted">[</span>
            <TrendingUp className="h-3.5 w-3.5 text-accent-green" />
            PORTFOLIO_PERF
            <span className="text-text-muted">]</span>
            <span className="text-[10px] text-text-muted font-normal">// 30 days</span>
          </h2>
          <PortfolioChart data={portfolio} height={300} />
        </div>

        {/* Activity feed — takes 1/3 */}
        <div className="card p-4 max-h-[420px] overflow-y-auto">
          <h2 className="text-xs font-bold text-foreground mb-4 flex items-center gap-2 font-mono">
            <span className="text-text-muted">[</span>
            <Activity className="h-3.5 w-3.5 text-accent-cyan" />
            LIVE_FEED
            <span className="text-text-muted">]</span>
            <span className="h-1.5 w-1.5 bg-accent-green animate-pulse-dot ml-auto" />
          </h2>
          <ActivityFeed logs={logs} maxItems={10} />
        </div>
      </div>

      {/* ---- Positions ---- */}
      <div className="mb-6">
        <h2 className="text-xs font-bold text-foreground mb-4 flex items-center gap-2 font-mono">
          <span className="text-text-muted">[</span>
          <BarChart3 className="h-3.5 w-3.5 text-accent-green" />
          ACTIVE_POSITIONS
          <span className="text-text-muted">]</span>
        </h2>
        <PositionsList positions={positions} />
      </div>

      {/* ---- Recent Trades ---- */}
      <div>
        <h2 className="text-xs font-bold text-foreground mb-4 flex items-center gap-2 font-mono">
          <span className="text-text-muted">[</span>
          <Zap className="h-3.5 w-3.5 text-accent-amber" />
          RECENT_TRADES
          <span className="text-text-muted">]</span>
        </h2>
        <TradeTable trades={trades} />
      </div>
    </ClientLayout>
  );
}
